### ISSUE TITLE
gulist crashing server

### ISSUE THREAD

**Issue by Bottomdollarnet** [ProjectInfinity/PocketVote#39]
[Thu_Jul_25-18.55.10-PDT_2019.log](https://github.com/ProjectInfinity/PocketVote/files/3437603/Thu_Jul_25-18.55.10-PDT_2019.log)

**Comment by ProjectInfinity** [comment]
Not caused by PocketVote. Read the crash log you submitted:

PocketMine-MP Crash Dump Thu Jul 25 18:55:10 PDT 2019

Error: Call to a member function getName() on null
File: plugins/BlazinHud.phar/src/iiFlamiinBlaze/BlazinHud/HudTask
Line: 60
Type: Error

**THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BlazinHud v1.0.5**
