### ISSUE TITLE
Detail API Document

### ISSUE THREAD

**Issue by codehz** [ProjectInfinity/PocketVote#47]
Hi, I'm developer of [ElementZero](https://github.com/Element-0/ElementZero) (third-party server based on official bedrock dedicated server), and I want to develop a PocketVote mod for it, but I cannot found detail API document for that -- like api.pocketvote.io/v2/check etc..
So are there any existing documents and instructions now? I think that studying the existing PMMP and nukkit plugins is not a good idea, I may miss some important information from the source code

**Comment by ProjectInfinity** [comment]
Hi, sorry I missed this due to the ongoing pandemic. 

There are no official documentation on supporting the backend but I highly suggest looking at the PHP plugin to see the API calls as the code itself is quite simple.

https://github.com/ProjectInfinity/PocketVote-PocketMine/tree/master/src/ProjectInfinity/PocketVote/task

Let me know if there's anything I can do to help.
